base_model: PLACEHOLDER
dtype: bfloat16
training_args:
  overwrite_output_dir: true
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  gradient_checkpointing: false
  learning_rate: 0.00002
  num_train_epochs: 1
  do_train: true
  max_steps: 2500
  optim: adafactor 
  lr_scheduler_type: cosine
  warmup_ratio : 0.1
  save_strategy: steps
  save_steps: 500
  bf16: false
  fp16: false
  logging_steps : 10
  push_to_hub: false
streaming: true
sequence_length: 512
watermark_datasets: 
  - OpenMathInstruct
alpha: 0.1666666666
regularization_datasets:
  - AlpacaGPT4
  - OpenWebText
loss_types:
  - anti-watermark-tv
  - anti-watermark-tv
proportions: 
  - 0.5
  - 0.1
  - 0.4
lambdas:
  - 1
  - 1
  - 1
custom_name: TV