name: "frenchQA_eval"
n_samples: 100
prompt_length: 100
min_token_length: 200
max_token_length: 200
dataset_config:
  path: "jpacifico/French-Alpaca-dataset-Instruct-55K"
  split: "train"
  data_fields: ["instruction", "output"]
batch_size: 16
compute_ppl: true
ppl_model: "meta-llama/Llama-3.1-8B-Instruct"