name: medicine_wiki
n_samples: 100
prompt_length: 50
min_token_length: 200
max_token_length: 200
dataset_config:
  path: "burgerbee/medicine_wiki"
  split: "train"
  data_field: "text"
batch_size: 16
compute_ppl: true
ppl_model: "meta-llama/Llama-3.1-8B-Instruct"