base_model: Qwen/Qwen2.5-3B-Instruct
caching_models: false

evaluate_original: false

watermark_evaluation_config: 
 - configs/eval/frenchQA_eval.yaml
 - configs/eval/math_watermark_eval.yaml
 - configs/eval/medicine_eval.yaml
 - configs/eval/generalQA_eval.yaml
watermark_type: kgw
watermark_config: "configs/watermarks/kgw/kgw_d4.yaml"
disable_wm_detector: false
overwrite_results: true

use_neptune: false

output_directory: "paper"
huggingface_name: 

finetuning_config: configs/paper/qwen2.5-3B/finetuning_config/health_ft.yaml