base_model: meta-llama/Llama-3.2-1B-Instruct
caching_models: false

evaluate_original: false

watermark_evaluation_config: 
 - configs/eval/math_watermark_eval.yaml
watermark_config: "configs/watermarks/kgw/kgw_d4.yaml"
disable_wm_detector: false
overwrite_results: true
watermark_type: kgw

use_neptune: false

output_directory: "paper"
huggingface_name: 

finetuning_config: configs/paper/llama3/finetuning_config/math_ft.yaml