name: "SF_fingerprint"
n_samples: 1024
prompt_length: 100
min_token_length: 200
max_token_length: 200
dataset_config:
  dataset_path: "datasets_folder/scalable/Llama-3.2-1B-Instruct"
  data_fields: ["prompt", "response"]
  is_local: true
batch_size: 16
compute_ppl: true
ppl_model: "meta-llama/Llama-3.1-8B-Instruct"